# Generated by Django 5.0.1 on 2024-04-17 08:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("link_collections", "0001_initial"),
        ("links", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="link",
            name="description",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="Краткое описание"
            ),
        ),
        migrations.AlterField(
            model_name="link",
            name="header",
            field=models.CharField(
                blank=True, default="", max_length=50, verbose_name="Заголовок страницы"
            ),
        ),
        migrations.AddConstraint(
            model_name="link",
            constraint=models.UniqueConstraint(fields=("link", "user"), name="unique_user_link"),
        ),
    ]
