# Generated by Django 5.0.1 on 2024-04-17 09:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("links", "0002_alter_link_description_alter_link_header_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="link",
            name="description",
            field=models.TextField(blank=True, default="", verbose_name="Краткое описание"),
        ),
    ]
