# Generated by Django 5.0.1 on 2024-04-17 09:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("links", "0003_alter_link_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="link",
            name="header",
            field=models.TextField(blank=True, default="", verbose_name="Заголовок страницы"),
        ),
    ]
